-- Audit table for every call to /api/alt-text and /api/alt-text/batch.
-- Powers /api/stats and is the foundation for per-IP rate limiting (v2.1).

CREATE TABLE request_audits (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endpoint        VARCHAR(64)  NOT NULL,
    client_ip_hash  VARCHAR(64)  NOT NULL,
    language        VARCHAR(8)   NOT NULL,
    images_count    SMALLINT     NOT NULL,
    total_bytes     BIGINT       NOT NULL,
    status_code     SMALLINT     NOT NULL,
    latency_ms      INTEGER      NOT NULL,
    model           VARCHAR(64),
    error_code      VARCHAR(64)
);

CREATE INDEX idx_request_audits_created_at
    ON request_audits (created_at DESC);

CREATE INDEX idx_request_audits_client_ip_hash_created_at
    ON request_audits (client_ip_hash, created_at DESC);
