-- Async batch jobs: clients submit images, get a job_id immediately, then poll
-- /api/jobs/{id} while a background worker processes the images one by one.

CREATE TABLE batch_jobs (
    id                UUID         PRIMARY KEY,
    client_ip_hash    VARCHAR(64)  NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at        TIMESTAMP WITH TIME ZONE,
    completed_at      TIMESTAMP WITH TIME ZONE,
    status            VARCHAR(16)  NOT NULL,
    language          VARCHAR(8)   NOT NULL,
    total_images      SMALLINT     NOT NULL,
    processed_images  SMALLINT     NOT NULL DEFAULT 0,
    model             VARCHAR(64)  NOT NULL,
    error_code        VARCHAR(64)
);

CREATE INDEX idx_batch_jobs_created_at ON batch_jobs (created_at DESC);
CREATE INDEX idx_batch_jobs_status     ON batch_jobs (status);

CREATE TABLE batch_job_items (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id        UUID         NOT NULL REFERENCES batch_jobs(id) ON DELETE CASCADE,
    position      SMALLINT     NOT NULL,
    file_name     VARCHAR(255),
    size_bytes    BIGINT       NOT NULL,
    alt_text      TEXT,
    language      VARCHAR(8),
    error_code    VARCHAR(64),
    completed_at  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_batch_job_items_job_id_position
    ON batch_job_items (job_id, position);
